version: "3.9"

services:
  api:
    container_name: lms-api
    build: .
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run dev"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    # command: npm run dev

  postgres:
    container_name: lms-postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    #   interval: 2s
    #   timeout: 2s
    #   retries: 30

  redis:
    container_name: lms-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: unless-stopped

  # rabbitmq:
  #   image: rabbitmq:management-alpine
  #   environment:
  #     # Pakai user non-guest (guest dibatasi ke localhost oleh RabbitMQ)
  #     RABBITMQ_DEFAULT_USER: appuser
  #     RABBITMQ_DEFAULT_PASS: appsecret
  #   ports:
  #     - "5672:5672"    # AMQP
  #     - "15672:15672"  # Management UI
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20

volumes:
  postgres_data:
  redis_data: